# Cargo audit configuration
[advisories]
# Allow unmaintained crates (warnings only, not errors)
unmaintained = "warn"

# License configuration
[licenses]
# Allow common open source licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 OR MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unlicense",
    "0BSD",
    "Zlib",
    "CC0-1.0",
    "MPL-2.0",
    "LGPL-2.1",
    "LGPL-3.0",
    "GPL-2.0",
    "GPL-3.0",
]

# Deny proprietary licenses
deny = [
    "proprietary",
    "commercial",
]

# Allow unknown licenses (for crates without explicit license info)
unknown = "warn"
