# Cross compilation configuration for GPU Kill
# This file configures cargo-cross to handle cross-compilation properly

# Global settings
[build.env]
# Allow cross-compilation
PKG_CONFIG_ALLOW_CROSS = "1"

# ARM64 Linux cross-compilation
[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/cross:aarch64-unknown-linux-gnu-0.2.5"

[target.aarch64-unknown-linux-gnu.env]
# ARM64 specific OpenSSL settings
OPENSSL_DIR = "/usr/aarch64-linux-gnu"
OPENSSL_INCLUDE_DIR = "/usr/aarch64-linux-gnu/include"
OPENSSL_LIB_DIR = "/usr/aarch64-linux-gnu/lib"
PKG_CONFIG_PATH = "/usr/aarch64-linux-gnu/lib/pkgconfig"

# Windows cross-compilation
[target.x86_64-pc-windows-gnu]
image = "ghcr.io/cross-rs/cross:x86_64-pc-windows-gnu-0.2.5"

[target.x86_64-pc-windows-gnu.env]
# Windows specific settings
PKG_CONFIG_ALLOW_CROSS = "1"
