# Cross compilation configuration for GPU Kill
# This file configures cargo-cross to handle cross-compilation properly

# ARM64 Linux cross-compilation
[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/cross:aarch64-unknown-linux-gnu-0.2.5"

# Windows cross-compilation  
[target.x86_64-pc-windows-gnu]
image = "ghcr.io/cross-rs/cross:x86_64-pc-windows-gnu-0.2.5"

# Global build environment
[build.env]
# Allow cross-compilation for pkg-config
PKG_CONFIG_ALLOW_CROSS = "1"
