name: Hot Aisle GPU Testing (Disabled)

# This workflow is currently disabled until Hot Aisle API key is configured
# To enable:
# 1. Set up HOTAISLE_API_KEY in GitHub Secrets
# 2. Rename hotaisle-gpu-testing.yml.disabled to hotaisle-gpu-testing.yml
# 3. Uncomment the triggers below

on:
  # workflow_dispatch:  # Uncomment when ready to use
    # inputs:
    #   gpu_types:
    #     description: 'Comma-separated GPU types to test (nvidia,amd,intel,apple-silicon)'
    #     required: false
    #     default: 'nvidia,amd,intel'
    #   test_duration:
    #     description: 'Test duration in minutes'
    #     required: false
    #     default: '30'

jobs:
  placeholder:
    name: Hot Aisle Integration Status
    runs-on: ubuntu-latest
    steps:
      - name: Check Hot Aisle Integration Status
        run: |
          echo "🔧 Hot Aisle GPU Testing is currently disabled"
          echo ""
          echo "To enable Hot Aisle GPU testing:"
          echo "1. Set up HOTAISLE_API_KEY in GitHub Secrets"
          echo "2. Rename hotaisle-gpu-testing.yml.disabled to hotaisle-gpu-testing.yml"
          echo "3. Uncomment the workflow triggers"
          echo ""
          echo "For now, use the 'Test Hot Aisle Integration' workflow to test the integration structure."
          echo "✅ Hot Aisle integration code is ready and tested!"
